#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
 
bash /home/zyyang/桌面/csp/clash.sh
bash /home/zyyang/桌面/sh/login.sh
exit 0
